### ISSUE TITLE
errors occurs when it comes to run the Charades-STA dataset. 

### ISSUE THREAD

**Issue by tongbaochen** [r-cui/ViGA#1]
Hi, thanks for your wonderful work , however, I have met the following error when I run the Charades-STA dataset (everything goes well when I run the other two datasets, tacos and activity net). Would you mind helping figure it out? Thanks.
-----------
errors log
-----------
Training epoch 1 with lr 0.0001:   0%|          | 0/24 [00:00<?, ?it/s]
Training epoch 1 with lr 0.0001:   0%|          | 0/24 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/data1/zhekun/anaconda3/envs/viga/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data1/zhekun/anaconda3/envs/viga/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data1/chentongbao/VCMR/ViGA/src/experiment/train.py", line 90, in <module>
    train(config)
  File "/data1/chentongbao/VCMR/ViGA/src/experiment/train.py", line 56, in train
    desc="Training epoch {} with lr {}".format(epoch, model.optimizer.param_groups[0]["lr"])
  File "/data1/zhekun/anaconda3/envs/viga/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/data1/zhekun/anaconda3/envs/viga/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/data1/zhekun/anaconda3/envs/viga/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/data1/zhekun/anaconda3/envs/viga/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/data1/zhekun/anaconda3/envs/viga/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data1/zhekun/anaconda3/envs/viga/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/data1/zhekun/anaconda3/envs/viga/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/data1/chentongbao/VCMR/ViGA/src/dataset/dataset.py", line 116, in collate_fn
    batch[k] = torch.stack(batch[k], dim=0)
RuntimeError: stack expects each tensor to be equal size, but got [87, 1, 42, 1024] at entry 0 and [72, 1, 57, 1024] at entry 1

**Comment by r-cui** [comment]
Hi Tongbao,

Thank you for your attention to our work. By my preliminary look at this error message, the bug is likely to occur from the extra dim 1 in your video features (.npy) of the Charades-STA dataset. To run ViGA smoothly, it is necessary to synchronize all the downloaded video features across all the datasets to the same format, i.e., (T, dim), as described in the readme of this repo.

Good luck,
Ran

**Comment by tongbaochen** [comment]
> Hi Tongbao,
> 
> Thank you for your attention to our work. By my preliminary look at this error message, the bug is likely to occur from the extra dim 1 in your video features (.npy) of the Charades-STA dataset. To run ViGA smoothly, it is necessary to synchronize all the downloaded video features across all the datasets to the same format, i.e., (T, dim), as described in the readme of this repo.
> 
> Good luck, Ran

Thanks a lot!

**Comment by tongbaochen** [comment]
fixed

**Comment by ccccwb** [comment]
Could you tell me how to do it？thank u very much
I dont konw how to make these different video features to the same format (T, dim)
I made the following attempt
1. I tried to get rid of the extra dim 1
`        for k in to_stack:
            for i, feat in enumerate(batch[k]):
                batch[k][i] = feat.squeeze() 
            batch[k] = torch.stack(batch[k], dim=0)`
But the error is as follows：
RuntimeError: stack expects each tensor to be equal size, but got [87, 42, 1024] at entry 0 and [72, 57, 1024] at entry 1

2. I try to reshape these features 
`        for k in to_stack:
            for i, feat in enumerate(batch[k]):
                batch[k][i] = feat.reshape(-1,1024)
            batch[k] = torch.stack(batch[k], dim=0)`
The error is as follows：
RuntimeError: stack expects each tensor to be equal size, but got [3654, 1024] at entry 0 and [4104, 1024] at entry 1

**Comment by Lonicer** [comment]
> Could you tell me how to do it？thank u very much I dont konw how to make these different video features to the same format (T, dim) I made the following attempt
> 
> 1. I tried to get rid of the extra dim 1
>    `        for k in to_stack: for i, feat in enumerate(batch[k]): batch[k][i] = feat.squeeze()  batch[k] = torch.stack(batch[k], dim=0)`
>    But the error is as follows：
>    RuntimeError: stack expects each tensor to be equal size, but got [87, 42, 1024] at entry 0 and [72, 57, 1024] at entry 1
> 2. I try to reshape these features
>    `        for k in to_stack: for i, feat in enumerate(batch[k]): batch[k][i] = feat.reshape(-1,1024) batch[k] = torch.stack(batch[k], dim=0)`
>    The error is as follows：
>    RuntimeError: stack expects each tensor to be equal size, but got [3654, 1024] at entry 0 and [4104, 1024] at entry 1

Have you solved it? I ran into the same problem as you.

**Comment by ccccwb** [comment]
> > Could you tell me how to do it？thank u very much I dont konw how to make these different video features to the same format (T, dim) I made the following attempt
> > 
> > 1. I tried to get rid of the extra dim 1
> >    `        for k in to_stack: for i, feat in enumerate(batch[k]): batch[k][i] = feat.squeeze()  batch[k] = torch.stack(batch[k], dim=0)`
> >    But the error is as follows：
> >    RuntimeError: stack expects each tensor to be equal size, but got [87, 42, 1024] at entry 0 and [72, 57, 1024] at entry 1
> > 2. I try to reshape these features
> >    `        for k in to_stack: for i, feat in enumerate(batch[k]): batch[k][i] = feat.reshape(-1,1024) batch[k] = torch.stack(batch[k], dim=0)`
> >    The error is as follows：
> >    RuntimeError: stack expects each tensor to be equal size, but got [3654, 1024] at entry 0 and [4104, 1024] at entry 1
> 
> Have you solved it? I ran into the same problem as you.

sry, i still can not solve it.
