### ISSUE TITLE
Charades-STA C3D feature Problem

### ISSUE THREAD

**Issue by Lonicer** [r-cui/ViGA#3]
1. Can you provide the predict.py file for extracting the c3d features of the Charades-STA dataset in the c3d warehouse you gave?
2. In addition, please tell ViGA how to change the read-in feature dimension to (T, 1024) when ViGA is trained based on Charadest-STA?

Many thanks!

**Comment by LeeRoc-China** [comment]
+1

**Comment by r-cui** [comment]
Hi Lonicer,

Sorry for the late reply, was busy on other works quite intensely.

For Q1, please refer to issue https://github.com/r-cui/ViGA/issues/2 where we replied about the availablity of C3D Charades-STA features.
For Q2, we prepared all features offline and saved the processed features on disk before any of the training codes runs. Please ensure you have the similar as described in the README, e.g., `Folder contains 9848 vid.npys, each of shape (T, 1024).`

Hope these help.
Ran
